export const themes = {
  '4-7': {
    id: '4-7',
    label: '4 – 7 ans',
    tagline: 'Je découvre le monde !',
    font: 'font-petits',
    bg: '#FFF8F0',
    bgGradient: 'linear-gradient(135deg, #FFF8F0 0%, #FFE8D6 50%, #FFDDC1 100%)',
    primary: '#FF6B6B',
    primaryLight: '#FF9A9A',
    secondary: '#FFD93D',
    secondaryLight: '#FFE88A',
    accent: '#51CF66',
    accentLight: '#8CE99A',
    cardBg: '#FFFFFF',
    cardBorder: '#FFE0E0',
    text: '#3D3D3D',
    textLight: '#7A7A7A',
    highlight: '#FFD93D',
    buttonRadius: '9999px',
    cardRadius: '24px',
    inputRadius: '20px',
    decorations: true,
    mascotName: 'Loutinou',
    questionPlaceholders: {
      curious: 'Dis-moi, dis-moi ! Qu\'est-ce que tu veux savoir ? 🌟',
      normal: 'Pose ta question ici, petit curieux... 🦦',
      tired: 'On y va doucement... quelle est ta question ? 💤',
    },
  },
  '8-11': {
    id: '8-11',
    label: '8 – 11 ans',
    tagline: 'J\'explore et je comprends !',
    font: 'font-moyens',
    bg: '#F0F4FF',
    bgGradient: 'linear-gradient(135deg, #F0F4FF 0%, #E4EAFF 50%, #DDE4FF 100%)',
    primary: '#7C5CFC',
    primaryLight: '#A78BFA',
    secondary: '#20C997',
    secondaryLight: '#63E6BE',
    accent: '#FFB347',
    accentLight: '#FFD28A',
    cardBg: '#FFFFFF',
    cardBorder: '#E0E4FF',
    text: '#2D3436',
    textLight: '#636E72',
    highlight: '#63E6BE',
    buttonRadius: '16px',
    cardRadius: '20px',
    inputRadius: '16px',
    decorations: true,
    mascotName: 'Loutrix',
    questionPlaceholders: {
      curious: 'Je suis super motivé ! C\'est quoi ta question ? 🚀',
      normal: 'Tape ta question ici... 🔍',
      tired: 'Pas de pression, pose ta question tranquille... 😌',
    },
  },
  '12-15': {
    id: '12-15',
    label: '12 – 15 ans',
    tagline: 'Je pense par moi-même.',
    font: 'font-grands',
    bg: '#F5F6F8',
    bgGradient: 'linear-gradient(135deg, #F5F6F8 0%, #EBEDF2 50%, #E5E7ED 100%)',
    primary: '#3B82F6',
    primaryLight: '#60A5FA',
    secondary: '#14B8A6',
    secondaryLight: '#5EEAD4',
    accent: '#F97316',
    accentLight: '#FB923C',
    cardBg: '#FFFFFF',
    cardBorder: '#E5E7EB',
    text: '#1F2937',
    textLight: '#6B7280',
    highlight: '#5EEAD4',
    buttonRadius: '12px',
    cardRadius: '16px',
    inputRadius: '12px',
    decorations: false,
    mascotName: 'Loutzen',
    questionPlaceholders: {
      curious: 'Envoie ta question, je suis chaud 🔥',
      normal: 'Pose ta question ici...',
      tired: 'Tranquille, à ton rythme... 💭',
    },
  },
};
